---
device: "cpu"
num_seeds: 10

dataset_name: "treviso-market-224_224"

train:
  network_type: "cnn" # ['cnn', 'pre_trained_cnn', 'pre_trained_vit']
  epochs: 10
  optimizer: "AdamW" # SGD, Adam, AdamW
  criterion: "CrossEntropyLoss" # NLLLoss, CrossEntropyLoss
  batch_size: 16
  learning_rate: 3.0e-05
  log_every: 1
  evaluate_every: 1
  early_stopping:
    patience: 50
    metrics: "macro_f1"
    metrics_trend: "increasing"
cv:
  k: 10
  use_cv_metadata: false
