model_name: MilaNLProc/hate-ita # "Hate-speech-CNERG/dehatebert-mono-italian
target_label: hateful # only for inference
test_size: 0.2

model_max_length: 128

device: 0
batch_size: 8
learning_rate: 1.0e-4
freeze_base: false

